name: Python package and test

on:
  push:
  pull_request:

jobs:
  checkout-test:
    name: Checkout and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create python 3.11 conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          mamba-version: "*"
          activate-environment: donkey
          auto-activate-base: false
          channels: default, conda-forge, pytorch
          channel-priority: true
      - name: Conda info and list
        run: |
          conda info
          conda list
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt','pyproject.toml','setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build package
        run: |
          make package
      - name: Install donkey
        run: |
          pip install dist/*.whl
          if [ -f requirements-pc.txt ]; then pip install -r requirements-pc.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip list
      - name: Run tests
        run: pytest
